"""add pinned and archived

Revision ID: 7db9e4eb8694
Revises: 20251224_0001
Create Date: 2025-12-24 15:03:50.126150

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7db9e4eb8694"
down_revision: Union[str, None] = "20251224_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note",
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "note",
        sa.Column("archived", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f("ix_note_archived"), "note", ["archived"], unique=False)
    op.create_index(op.f("ix_note_pinned"), "note", ["pinned"], unique=False)

    op.alter_column("note", "pinned", server_default=None)
    op.alter_column("note", "archived", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_pinned"), table_name="note")
    op.drop_index(op.f("ix_note_archived"), table_name="note")
    op.drop_column("note", "archived")
    op.drop_column("note", "pinned")
    # ### end Alembic commands ###
